<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<div class="mage-magictabs mc-<?php echo $this->getTypeFilter();?>">
<?php $total = $_productCollection->count() ?>
<?php if (!$total): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php //echo $block->getAdditionalHtml() ?>
    <?php
    // if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    // } else {
    //     $viewMode = 'list';
    //     $image = 'category_page_list';
    //     $showDescription = true;
    //     $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    // }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php 
        $config     = $this->getWidgetCfg(); 
        // $width      = $config['widthImages'];
        // $height     = $config['heightImages'];
        $showCart       = $config['cart'];
        $showCompare    = $config['compare'];
        $showWishlist   = $config['wishlist'];
        $showReview     = $config['review'];
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
				<?php if($iterator%5==1) echo '<div class="product product-items">'; ?>
				<?php /* if($iterator%5==1 || $iterator%5==0) echo '<div class="sub-item item product-item">'; // 4-1 */ ?>
                <?php if($iterator%5==1 || $iterator%5==4 || $iterator%5 == 3) echo '<div class="sub-item item product-item">';  /* 2-1-2*/ ?>
                <div class="product-item-info" data-container="product-grid">
                    <div class="per-product">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
					<div class="link-view">
						 <button type="button" class="quickview"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><i class="pe-icon pe-7s-search icons"></i><?php //echo __('Quick View')?></span>
						 </button>
					</div>
                    <div class="images-container">
                        <?php // Product Image ?>
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                        <h2 class="product-name">
                            <a class="product-item-link" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                        <div class="product-hover">
                            <?php echo $_aloHelper->getLabels($_product); ?>
                            <?php //echo $_aloHelper->getTimer($_product); ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        </div>
                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                            <div class="hover-box">
                                <div class="product actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <?php echo $block->getProductPrice($_product) ?>
                                    <!-- cart -->
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart">
                                                        <i class="icon icon-add-to-cart"></i><span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <!-- end cart -->
                                    <!-- wishlist/compare -->
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            
                                            <?php if ($showCompare): $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#"
                                                   class="action tocompare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <i class="icon icon-compare"></i><?php /* @escapeNotVerified */ echo __('Compare') ?>
                                                </a>
                                            <?php endif; ?>

                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <i class="icon icon-favorites"></i><?php /* @escapeNotVerified */ echo __('Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                            <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                        </div>
                                    <?php endif; ?>
                                    <!-- end wishlist/compare -->
                                </div>
                            </div>
                        <?php endif; ?>
                            
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <!-- description -->
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                            <!-- end description -->
                    </div>
                    </div>
                </div>
                <?php if($iterator%5==0 || $iterator%5==2 || $iterator%5 == 3 || $iterator==$total) echo '</div>'; /* 2-1-2 */ ?>
				<?php /* if($iterator%5==0 || $iterator%5==4 || $iterator==$total) echo '</div>'; // 4-1 */ ?>
				<?php if($iterator%5==0 || $iterator==$total) echo '</div>'; $iterator++;?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php // echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
</div>
