<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php echo $class; ?>-products-post" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">

        <div class="products wrapper grid products-grid blog-detail products-<?php echo $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info per-product <?php echo $available; ?>">
				    <div class="images-container">
				    	<h2 class="product-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
							<?php echo $block->escapeHtml($_item->getName()) ?></a>
						</h2>
						<div class="product-hover">
							<a href="<?php echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
								<?php echo $block->getImage($_item, $image)->toHtml(); ?>
							</a>
						</div>
						<div class="hover-box">
							<a class="detail_links" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"></a>
								<?php if ($showWishlist || $showCompare || $showCart): ?>
									<div class="product actions">
										<?php echo $block->getProductPrice($_item); ?>
										<?php if ($showCart): ?>
											<div class="actions-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary button btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
															<i class="icon icon-add-to-cart"></i><span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary button btn-cart"
																data-post='<?php echo $postData; ?>'
																type="button" title="<?php echo __('Add to Cart') ?>">
															<i class="icon icon-add-to-cart"></i><span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php endif; ?>

										<?php if ($showWishlist || $showCompare): ?>
											<div class="secondary-addto-links add-to-links actions-secondary" data-role="add-to-links">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<a href="#" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
														<i class="icon icon-favorites"></i>
                                                        <?php echo __('Wishlist') ?>
													</a>
												<?php endif; ?>
												<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<a href="#" class="action tocompare"
													   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
													   data-role="add-to-links"
													   title="<?php echo __('Add to Compare'); ?>">
														<i class="icon icon-compare"></i>
                                                        <?php echo __('Compare') ?>
													</a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
								<?php endif; ?>
						</div>
                    </div>
					<div class="product details products-textlink product-item-details">
						
						
						<?php if ($templateType): ?>
							<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
						<?php endif; ?>
					</div>
				</div>
                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>