<?php $welcomeMessage = $block->getWelcome(); ?>
<div class="welcome greet welcome-msg" data-bind="scope: 'customer'">
	<!-- ko if: customer().fullname  -->
	<span class="welcome-title" data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
	</span>
	<!-- /ko -->
	<!-- ko ifnot: customer().fullname  -->
	<span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
	<!-- /ko -->
</div>


<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"customer": {
					"component": "Magento_Customer/js/view/customer"
				}
			}
		}
	}
}
</script>